// Command catalogsync regenerates catalog/services.json and the per-service guide
// pages under templates/guides from the full OSC catalog. It needs an OSC API key
// (OSC_API_KEY); end users do not have one, which is why the result is committed.
//
//	OSC_API_KEY=... go run ./cmd/catalogsync
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"time"

	"terraform-provider-osc/internal/catalog"
)

const marker = "<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->"

type rawService struct {
	ServiceID string `json:"serviceId"`
	Metadata  struct {
		Title            string `json:"title"`
		Description      string `json:"description"`
		Category         string `json:"category"`
		DocumentationURL string `json:"documentationUrl"`
		RepoURL          string `json:"repoUrl"`
	} `json:"serviceMetadata"`
	APIURL      string           `json:"apiUrl"`
	Options     []catalog.Option `json:"serviceInstanceOptions"`
	ServiceType string           `json:"serviceType"`
	Status      string           `json:"status"`
}

func main() {
	out := flag.String("out", "catalog/services.json", "path of the JSON mirror to write")
	guides := flag.String("guides", "templates/guides", "directory for generated guide templates")
	env := flag.String("environment", envOr("OSC_ENVIRONMENT", "prod"), "OSC environment")
	flag.Parse()

	apiKey := os.Getenv("OSC_API_KEY")
	if apiKey == "" {
		fatal("OSC_API_KEY is not set")
	}

	raw, err := fetchCatalog(*env, apiKey)
	if err != nil {
		fatal("fetching catalog: %v", err)
	}
	services := convert(raw)
	if len(services) == 0 {
		fatal("catalog returned no published services; refusing to write an empty mirror")
	}

	mirror := catalog.Mirror{GeneratedAt: time.Now().UTC().Truncate(time.Second), Environment: *env, Services: services}
	if prev, err := readMirror(*out); err == nil && reflect.DeepEqual(prev.Services, services) {
		mirror.GeneratedAt = prev.GeneratedAt // unchanged content keeps its timestamp
	}
	if err := writeJSON(*out, mirror); err != nil {
		fatal("writing mirror: %v", err)
	}

	written, removed, err := writeGuides(*guides, services)
	if err != nil {
		fatal("writing guides: %v", err)
	}
	fmt.Printf("%d services in %s, %d guide pages written, %d stale guide pages removed\n", len(services), *out, written, removed)
}

func envOr(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func fatal(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, "catalogsync: "+format+"\n", args...)
	os.Exit(1)
}

func fetchCatalog(env, apiKey string) ([]rawService, error) {
	req, err := http.NewRequest(http.MethodGet, fmt.Sprintf("https://catalog.svc.%s.osaas.io/service", env), nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Authorization", "Bearer "+apiKey)
	req.Header.Set("Accept", "application/json")
	resp, err := (&http.Client{Timeout: 60 * time.Second}).Do(req)
	if err != nil {
		return nil, err
	}
	defer func() { _ = resp.Body.Close() }()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("HTTP %d: %s", resp.StatusCode, strings.TrimSpace(string(body)))
	}
	var raw []rawService
	if err := json.Unmarshal(body, &raw); err != nil {
		return nil, err
	}
	return raw, nil
}

func convert(raw []rawService) []catalog.Service {
	var out []catalog.Service
	for _, r := range raw {
		if r.Status != "PUBLISHED" || r.ServiceID == "" {
			continue
		}
		opts := r.Options
		if opts == nil {
			opts = []catalog.Option{}
		}
		out = append(out, catalog.Service{
			ServiceID:        r.ServiceID,
			Title:            strings.TrimSpace(r.Metadata.Title),
			Description:      strings.TrimSpace(r.Metadata.Description),
			Category:         r.Metadata.Category,
			DocumentationURL: r.Metadata.DocumentationURL,
			RepoURL:          r.Metadata.RepoURL,
			ServiceType:      r.ServiceType,
			Status:           r.Status,
			APIURL:           r.APIURL,
			Options:          opts,
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ServiceID < out[j].ServiceID })
	return out
}

func readMirror(path string) (*catalog.Mirror, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var m catalog.Mirror
	if err := json.Unmarshal(b, &m); err != nil {
		return nil, err
	}
	return &m, nil
}

func writeJSON(path string, v interface{}) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}

// writeGuides renders one tfplugindocs guide template per instance service and removes
// generated pages for services that are no longer published.
func writeGuides(dir string, services []catalog.Service) (written, removed int, err error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return 0, 0, err
	}
	keep := map[string]bool{}
	for _, s := range services {
		if s.ServiceType != "" && s.ServiceType != "instance" {
			continue
		}
		name := catalog.GuideSlug(s.ServiceID) + ".md.tmpl"
		keep[name] = true
		if err := os.WriteFile(filepath.Join(dir, name), []byte(renderGuide(s)), 0o644); err != nil {
			return written, removed, err
		}
		written++
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return written, removed, err
	}
	for _, e := range entries {
		if e.IsDir() || keep[e.Name()] {
			continue
		}
		b, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil || !bytes.Contains(b, []byte(marker)) {
			continue // hand written guide, leave it alone
		}
		if err := os.Remove(filepath.Join(dir, e.Name())); err != nil {
			return written, removed, err
		}
		removed++
	}
	return written, removed, nil
}

var nonWord = regexp.MustCompile(`[^A-Za-z0-9]+`)

// tmpl escapes text for inclusion in a Go template: "{{" would otherwise start an action.
func tmpl(s string) string { return strings.ReplaceAll(s, "{{", `{{"{{"}}`) }

func cell(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	s = strings.Join(strings.Fields(s), " ")
	return tmpl(s)
}

func firstSentence(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	if i := strings.Index(s, ". "); i > 0 && i < 200 {
		return s[:i+1]
	}
	if len(s) > 200 {
		return s[:197] + "..."
	}
	return s
}

func snake(name string) string {
	var b strings.Builder
	for i, r := range name {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteRune(r + ('a' - 'A'))
		} else {
			b.WriteRune(r)
		}
	}
	return strings.Trim(nonWord.ReplaceAllString(b.String(), "_"), "_")
}

func placeholder(o catalog.Option) string {
	switch {
	case len(o.Enum) > 0:
		return fmt.Sprintf("%q", o.Enum[0])
	case o.Type == "boolean":
		if o.Default != "" {
			return fmt.Sprintf("%q", o.Default)
		}
		return `"true"`
	case o.Default != "":
		return fmt.Sprintf("%q", o.Default)
	default:
		return `"..."`
	}
}

func renderGuide(s catalog.Service) string {
	var b strings.Builder
	title := s.Title
	if title == "" {
		title = s.ServiceID
	}
	desc := s.Description
	if desc == "" {
		desc = fmt.Sprintf("Instances of the %s service on Eyevinn Open Source Cloud.", title)
	}

	fmt.Fprintf(&b, "---\npage_title: %q\nsubcategory: \"Services\"\ndescription: |-\n  %s\n---\n%s\n\n",
		s.ServiceID+": "+title, tmpl(firstSentence(desc)), marker)
	fmt.Fprintf(&b, "# %s (`%s`)\n\n%s\n\n", tmpl(title), s.ServiceID, tmpl(desc))

	var links []string
	if s.DocumentationURL != "" {
		links = append(links, fmt.Sprintf("[Service documentation](%s)", s.DocumentationURL))
	}
	if s.RepoURL != "" {
		links = append(links, fmt.Sprintf("[Source](%s)", s.RepoURL))
	}
	if len(links) > 0 {
		fmt.Fprintf(&b, "%s\n\n", strings.Join(links, " · "))
	}

	// Split options.
	var nameOpt *catalog.Option
	var required, optional, sensitive []catalog.Option
	for i := range s.Options {
		o := s.Options[i]
		switch {
		case o.Name == "name":
			nameOpt = &s.Options[i]
		case o.Sensitive:
			sensitive = append(sensitive, o)
		case o.Mandatory:
			required = append(required, o)
		default:
			optional = append(optional, o)
		}
	}

	b.WriteString("## Example\n\n```terraform\n")
	fmt.Fprintf(&b, "resource \"osc_instance\" \"example\" {\n  service_id = %q\n  name       = \"my%s\"\n", s.ServiceID, shortName(s.ServiceID))
	if len(required)+len(optional) > 0 {
		b.WriteString("\n  parameters = {\n")
		w := 0
		for _, o := range append(append([]catalog.Option{}, required...), optional...) {
			if len(o.Name) > w {
				w = len(o.Name)
			}
		}
		for _, o := range required {
			fmt.Fprintf(&b, "    %-*s = %s\n", w, o.Name, tmpl(placeholder(o)))
		}
		for _, o := range optional {
			fmt.Fprintf(&b, "    # %-*s = %s\n", w, o.Name, tmpl(placeholder(o)))
		}
		b.WriteString("  }\n")
	}
	if len(sensitive) > 0 {
		b.WriteString("\n  sensitive_parameters = {\n")
		for _, o := range sensitive {
			fmt.Fprintf(&b, "    %s = var.%s\n", o.Name, snake(o.Name))
		}
		b.WriteString("  }\n")
	}
	b.WriteString("}\n```\n\n")
	b.WriteString("Commented lines are optional parameters. Values marked `\"...\"` need a real value. " +
		"Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.\n\n")

	b.WriteString("## Parameters\n\n")
	if len(s.Options) <= 1 {
		b.WriteString("This service takes no parameters besides `name`.\n\n")
	} else {
		b.WriteString("| Name | Type | Required | Description |\n|---|---|---|---|\n")
		for _, o := range s.Options {
			if o.Name == "name" {
				continue
			}
			req := "no"
			if o.Mandatory {
				req = "yes"
			}
			var notes []string
			if o.Description != "" {
				notes = append(notes, cell(o.Description))
			}
			if len(o.Enum) > 0 {
				notes = append(notes, "Allowed: `"+strings.Join(o.Enum, "`, `")+"`.")
			}
			if o.Default != "" {
				notes = append(notes, fmt.Sprintf("Default `%s`.", cell(o.Default)))
			}
			if o.RegexValidator != "" {
				notes = append(notes, fmt.Sprintf("Pattern `%s`.", cell(o.RegexValidator)))
			}
			if o.Sensitive {
				notes = append(notes, "Sensitive, set it in `sensitive_parameters`.")
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", o.Name, o.Type, req, strings.Join(notes, " "))
		}
		b.WriteString("\n")
	}

	if nameOpt != nil && nameOpt.RegexValidator != "" {
		fmt.Fprintf(&b, "The instance `name` must match `%s`", tmpl(nameOpt.RegexValidator))
		b.WriteString(" and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.\n\n")
	}
	b.WriteString("Parameter values are strings; booleans take `\"true\"` or `\"false\"`. Reference an `osc_secret` " +
		"as `osc_secret.<name>.ref` to keep a value out of the instance configuration. " +
		"This page is generated from the OSC catalog; the provider validates against the live catalog when planning.\n")
	return b.String()
}

func shortName(serviceID string) string {
	parts := strings.Split(serviceID, "-")
	last := parts[len(parts)-1]
	return strings.ToLower(nonWord.ReplaceAllString(last, ""))
}
