---
page_title: "ablindberg-adserver-frontend: Test Adserver UI"
subcategory: "Services"
description: |-
  Transform your ad operations with our React frontend for Eyevinn Test AdServer.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Test Adserver UI (`ablindberg-adserver-frontend`)

Transform your ad operations with our React frontend for Eyevinn Test AdServer. Effortlessly manage sessions, generate VAST/VMAP ads, and delve into insightful analytics—all in real-time!

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Test-Adserver.html) · [Source](https://github.com/ABLindberg/adserver-frontend)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "ablindberg-adserver-frontend"
  name       = "myfrontend"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
