---
page_title: "ablindberg-osc-vmaf-studio: VMAF Studio"
subcategory: "Services"
description: |-
  Transform your video quality assessment with OSC VMAF Studio, a cloud-based tool leveraging OSC and Eyevinn EasyVMAF.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# VMAF Studio (`ablindberg-osc-vmaf-studio`)

Transform your video quality assessment with OSC VMAF Studio, a cloud-based tool leveraging OSC and Eyevinn EasyVMAF. Enjoy effortless S3 storage management, detailed VMAF analysis, and secure credentials.

[Source](https://github.com/ABLindberg/osc-vmaf-studio)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "ablindberg-osc-vmaf-studio"
  name       = "mystudio"

  sensitive_parameters = {
    oscAccessToken = var.osc_access_token
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `oscAccessToken` | string | no | Personal Access Token for authenticating with OSC (Open Source Cloud) services, specifically required for accessing Eyevinn EasyVMAF service that performs the VMAF video quality analysis Sensitive, set it in `sensitive_parameters`. |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
