---
page_title: "alexbj75-movierecommendator: movierecommendator"
subcategory: "Services"
description: |-
  Discover new films effortlessly! Enter a movie name and get two personalized recommendations powered by OpenAI.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# movierecommendator (`alexbj75-movierecommendator`)

Discover new films effortlessly! Enter a movie name and get two personalized recommendations powered by OpenAI. Transform your movie nights with Movie Recommender’s smart suggestions. Try it now!

[Source](https://github.com/alexbj75/movierecommendator)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "alexbj75-movierecommendator"
  name       = "mymovierecommendator"

  parameters = {
    # OpenAiKey    = "..."
    # ClaudeApiKey = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `OpenAiKey` | string | no |  |
| `ClaudeApiKey` | string | no |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
