---
page_title: "alexbj75-alextodolist: alextodolist"
subcategory: "Services"
description: |-
  Boost your productivity with our full-stack Todo List Application! Featuring a sleek UI, robust Node.js backend, and seamless MariaDB integration, it's the perfect tool for managing tasks effortles...
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# alextodolist (`alexbj75-alextodolist`)

Boost your productivity with our full-stack Todo List Application! Featuring a sleek UI, robust Node.js backend, and seamless MariaDB integration, it's the perfect tool for managing tasks effortlessly.

[Source](https://github.com/alexbj75/alextodolist)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "alexbj75-alextodolist"
  name       = "myalextodolist"

  parameters = {
    dbHost     = "..."
    dbPort     = "..."
    dbUser     = "..."
    dbPassword = "..."
    dbName     = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `dbHost` | string | yes |  |
| `dbPort` | string | yes |  |
| `dbUser` | string | yes |  |
| `dbPassword` | string | yes |  |
| `dbName` | string | yes |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
