---
page_title: "anderswassen-chaosproxy-config: Chaos Stream Proxy Configurator"
subcategory: "Services"
description: |-
  Revolutionize your streaming experience with the Chaos Stream Proxy Configurator! Customize HLS streams with precision-timed delays for enhanced content manipulation and control effortlessly.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Chaos Stream Proxy Configurator (`anderswassen-chaosproxy-config`)

Revolutionize your streaming experience with the Chaos Stream Proxy Configurator! Customize HLS streams with precision-timed delays for enhanced content manipulation and control effortlessly.

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Chaos-Stream-Proxy.html) · [Source](https://github.com/anderswassen/chaosproxy-config)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "anderswassen-chaosproxy-config"
  name       = "myconfig"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
