---
page_title: "apache-airflow: Airflow"
subcategory: "Services"
description: |-
  Discover Apache Airflow, the ultimate platform for programmatically authoring, scheduling, and monitoring workflows.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Airflow (`apache-airflow`)

Discover Apache Airflow, the ultimate platform for programmatically authoring, scheduling, and monitoring workflows. Transform complex tasks into manageable, streamlined operations with dynamic and extensible DAGs. Enhance your workflow efficiency today!

[Source](https://github.com/apache/airflow)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "apache-airflow"
  name       = "myairflow"

  parameters = {
    # AdminPassword = "..."
    # DatabaseUrl   = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `AdminPassword` | string | no | Password for the administrative user account in Apache Airflow. This is typically used to access the web UI and perform administrative operations. |
| `DatabaseUrl` | string | no | Connection string for the metadata database that Airflow uses to store DAG information, task states, and other operational data. Supports PostgreSQL, MySQL, and SQLite databases. |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
