---
page_title: "apache-couchdb: Couch DB"
subcategory: "Services"
description: |-
  Unlock seamless data management with Apache CouchDB! Effortlessly scalable and highly available, CouchDB makes storing, retrieving, and syncing data across devices a breeze.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Couch DB (`apache-couchdb`)

Unlock seamless data management with Apache CouchDB! Effortlessly scalable and highly available, CouchDB makes storing, retrieving, and syncing data across devices a breeze. Ideal for modern cloud apps!

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-CouchDB.html) · [Source](https://github.com/apache/couchdb)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "apache-couchdb"
  name       = "mycouchdb"

  sensitive_parameters = {
    AdminPassword = var.admin_password
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `AdminPassword` | string | yes | Choose a password for administrator Sensitive, set it in `sensitive_parameters`. |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
