---
page_title: "atmoz-sftp: SFTP Server"
subcategory: "Services"
description: |-
  Effortlessly manage secure file transfers with our user-friendly SFTP server powered by OpenSSH.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# SFTP Server (`atmoz-sftp`)

Effortlessly manage secure file transfers with our user-friendly SFTP server powered by OpenSSH. Ideal for sharing files securely using SSH, it integrates easily with Docker, ensuring both security and simplicity.

[Source](https://github.com/atmoz/sftp)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "atmoz-sftp"
  name       = "mysftp"

  parameters = {
    Username = "..."
    Password = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `Username` | string | yes | The username for the SFTP user account that will be created in the container |
| `Password` | string | yes | The password for the SFTP user account, used for authentication when logging in via SFTP |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
