---
page_title: "binwiederhier-ntfy: ntfy"
subcategory: "Services"
description: |-
  Elevate your communication game with ntfy.sh! Effortlessly send push notifications to any device using simple HTTP requests.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# ntfy (`binwiederhier-ntfy`)

Elevate your communication game with ntfy.sh! Effortlessly send push notifications to any device using simple HTTP requests. Stay connected without sign-ups or fees. Perfect for automation and alerts!

[Source](https://github.com/binwiederhier/ntfy)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "binwiederhier-ntfy"
  name       = "myntfy"

  parameters = {
    databaseUrl = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `databaseUrl` | string | yes | Database connection URL for ntfy's persistent storage. Based on the project structure, ntfy supports both SQLite and PostgreSQL databases for storing messages, user data, subscriptions, and other persistent information. |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
