---
page_title: "birme-captcha-svc: Captcha Service"
subcategory: "Services"
description: |-
  Enhance your security effortlessly with our reliable CAPTCHA Service! Easily generate and verify CAPTCHAs to protect against automated attacks.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Captcha Service (`birme-captcha-svc`)

Enhance your security effortlessly with our reliable CAPTCHA Service! Easily generate and verify CAPTCHAs to protect against automated attacks. Quick setup, seamless integration, robust solution!

[Source](https://github.com/birme/captcha-svc)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "birme-captcha-svc"
  name       = "mysvc"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
