---
page_title: "birme-browserhand: Browserhand"
subcategory: "Services"
description: |-
  Experience seamless and reliable web automation for AI agents with Browserhand.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Browserhand (`birme-browserhand`)

Experience seamless and reliable web automation for AI agents with Browserhand. Execute tasks with precision, using stable element references instead of brittle selectors. Snapshot, act, recover, and reuse effortlessly, ensuring consistent automation in real browsing environments. Perfect for developers seeking robust and deterministic browser automation.

[Source](https://github.com/birme/browserhand)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "birme-browserhand"
  name       = "mybrowserhand"

  parameters = {
    # MaxConcurrentSessions = "..."
    # SessionTimeoutMs      = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `MaxConcurrentSessions` | string | no | Configuration option for maxconcurrentsessions |
| `SessionTimeoutMs` | string | no | Timeout value in milliseconds or seconds |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
