---
page_title: "birme-video-uploader: S3 Video Uploader"
subcategory: "Services"
description: |-
  Effortlessly upload and manage your videos with our intuitive Video Uploader.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# S3 Video Uploader (`birme-video-uploader`)

Effortlessly upload and manage your videos with our intuitive Video Uploader. Enjoy seamless drag-and-drop functionality, real-time upload tracking, and support for large files, all on your preferred S3-compatible storage.

[Source](https://github.com/birme/video-uploader)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "birme-video-uploader"
  name       = "myuploader"

  parameters = {
    s3AccessKey = "..."
    s3SecretKey = "..."
    # s3Endpoint  = "..."
    # s3AwsRegion = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `s3Endpoint` | string | no | Your S3 bucket endpoint URL |
| `s3AccessKey` | string | yes | Your AWS access key (like a username) |
| `s3SecretKey` | string | yes | Your AWS secret key (like a password) |
| `s3AwsRegion` | string | no | AWS region (e.g., eu-north-1) |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
