---
page_title: "birme-lambda: lambda"
subcategory: "Services"
description: |-
  Effortlessly deploy JavaScript/TypeScript code as HTTP-based lambda functions with our simple solution.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# lambda (`birme-lambda`)

Effortlessly deploy JavaScript/TypeScript code as HTTP-based lambda functions with our simple solution. Just zip, upload, and watch your code run on any HTTP request. Get started quickly with minimal setup!

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Birme-Lambda.html) · [Source](https://github.com/birme/lambda)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "birme-lambda"
  name       = "mylambda"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
