---
page_title: "bluesky-social-pds: Bluesky Personal Data Server"
subcategory: "Services"
description: |-
  Empower your network with self-hosted Bluesky PDS! Harness the power of AT Protocol to easily manage your data server.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Bluesky Personal Data Server (`bluesky-social-pds`)

Empower your network with self-hosted Bluesky PDS! Harness the power of AT Protocol to easily manage your data server. Seamless installation, full control, and enhanced security for your social media presence.

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Bluesky-Personal-Data-Server.html) · [Source](https://github.com/bluesky-social/pds)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "bluesky-social-pds"
  name       = "mypds"

  parameters = {
    AdminPassword    = "..."
    # DnsName          = "..."
    # EmailSmtpUrl     = "..."
    # EmailFromAddress = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `AdminPassword` | string | yes | Administrative password for PDS admin operations and account management |
| `DnsName` | string | no | Public DNS hostname for the PDS server that clients will use to connect |
| `EmailSmtpUrl` | string | no | SMTP server URL for sending verification emails and other notifications to users |
| `EmailFromAddress` | string | no | Email address that appears as the sender for emails sent by the PDS |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
