---
page_title: "burke-software-glitchtip: GlitchTip"
subcategory: "Services"
description: |-
  Seamlessly monitor and track app issues with GlitchTip! Experience smooth deployment on DigitalOcean or Heroku, complete with robust backend and frontend integration, plus Postgres and Redis flexib...
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# GlitchTip (`burke-software-glitchtip`)

Seamlessly monitor and track app issues with GlitchTip! Experience smooth deployment on DigitalOcean or Heroku, complete with robust backend and frontend integration, plus Postgres and Redis flexibility.

[Source](https://github.com/burke-software/GlitchTip)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "burke-software-glitchtip"
  name       = "myglitchtip"

  parameters = {
    secretKey   = "..."
    databaseUrl = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `secretKey` | string | yes |  |
| `databaseUrl` | string | yes |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
