---
page_title: "chatwoot-chatwoot: Chatwoot"
subcategory: "Services"
description: |-
  Transform your customer service with Chatwoot, the open-source platform that centralizes conversations across channels.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Chatwoot (`chatwoot-chatwoot`)

Transform your customer service with Chatwoot, the open-source platform that centralizes conversations across channels. Empower your team with AI-driven support, omnichannel integration, and insightful analytics.

[Source](https://github.com/chatwoot/chatwoot)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "chatwoot-chatwoot"
  name       = "mychatwoot"

  parameters = {
    DatabaseUrl       = "..."
    RedisUrl          = "..."
    # SmtpAddress       = "..."
    # SmtpPort          = "..."
    # SmtpUsername      = "..."
    # SmtpPassword      = "..."
    # MailerSenderEmail = "..."
  }

  sensitive_parameters = {
    SecretKeyBase = var.secret_key_base
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `DatabaseUrl` | string | yes | Database connection URL for PostgreSQL database that stores all Chatwoot data including conversations, contacts, agents, and configuration |
| `RedisUrl` | string | yes | Redis connection URL used for caching, session storage, background job processing, and real-time features like live chat |
| `SecretKeyBase` | string | yes | Rails application secret key used for encrypting sessions, cookies, and other sensitive data within the application Sensitive, set it in `sensitive_parameters`. |
| `SmtpAddress` | string | no | SMTP server hostname or IP address for sending outbound emails including notifications, password resets, and conversation replies |
| `SmtpPort` | string | no | SMTP server port number for email delivery, typically 587 for TLS or 465 for SSL connections |
| `SmtpUsername` | string | no | Username for authenticating with the SMTP server when sending emails from Chatwoot |
| `SmtpPassword` | string | no | Password or app-specific password for SMTP server authentication when sending emails |
| `MailerSenderEmail` | string | no | Email address that appears as the sender for all outbound emails from Chatwoot including notifications and system messages |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
