---
page_title: "clickhouse-clickhouse: ClickHouse Server"
subcategory: "Services"
description: |-
  Unlock real-time data insights effortlessly with ClickHouse, the lightning-fast, open-source columnar database.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# ClickHouse Server (`clickhouse-clickhouse`)

Unlock real-time data insights effortlessly with ClickHouse, the lightning-fast, open-source columnar database. Elevate your analytics and make data-driven decisions with speed and precision like never before!

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-ClickHouse.html) · [Source](https://github.com/ClickHouse/ClickHouse)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "clickhouse-clickhouse"
  name       = "myclickhouse"

  parameters = {
    # Db       = "..."
    # User     = "..."
    # Password = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `Db` | string | no | Database connection configuration |
| `User` | string | no | Configuration option for user |
| `Password` | string | no | Configuration option for password |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
