---
page_title: "dicedb-dice: Dice DB"
subcategory: "Services"
description: |-
  Experience real-time data management with DiceDB, the open-source, redis-compliant, reactive cache.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Dice DB (`dicedb-dice`)

Experience real-time data management with DiceDB, the open-source, redis-compliant, reactive cache. Its scalable and multithreaded architecture enhances modern hardware utilization, perfect for cutting-edge applications.

[Source](https://github.com/DiceDB/dice)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "dicedb-dice"
  name       = "mydice"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
