---
page_title: "encore: SVT Encore"
subcategory: "Services"
description: |-
  SVT Encore is an open-source video transcoding system for efficient cloud-based video processing.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# SVT Encore (`encore`)

SVT Encore is an open-source video transcoding system for efficient cloud-based video processing. It offers scalable, automated transcoding to optimize video workflows for various platforms, supporting multiple formats and codecs. With a focus on cost-effectiveness and flexibility, Encore is ideal for broadcasters and content creators needing dynamic scaling and reliable performance in their video production and distribution processes.

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-SVT-Encore.html) · [Source](https://github.com/svt/encore)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "encore"
  name       = "myencore"

  parameters = {
    # profilesUrl = "..."
    # s3Region    = "..."
    # s3Endpoint  = "..."
  }

  sensitive_parameters = {
    s3AccessKeyId = var.s3_access_key_id
    s3SecretAccessKey = var.s3_secret_access_key
    s3SessionToken = var.s3_session_token
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `profilesUrl` | string | no | URL pointing to list of transcoding profiles |
| `s3AccessKeyId` | string | no | Sensitive, set it in `sensitive_parameters`. |
| `s3SecretAccessKey` | string | no | Sensitive, set it in `sensitive_parameters`. |
| `s3SessionToken` | string | no | Sensitive, set it in `sensitive_parameters`. |
| `s3Region` | string | no |  |
| `s3Endpoint` | string | no |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
