---
page_title: "excalidraw-excalidraw: Excalidraw"
subcategory: "Services"
description: |-
  Transform your creative process with Excalidraw, the ultimate open-source whiteboard perfect for collaborative, hand-drawn style designs.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Excalidraw (`excalidraw-excalidraw`)

Transform your creative process with Excalidraw, the ultimate open-source whiteboard perfect for collaborative, hand-drawn style designs. Enjoy infinite canvas, customizable tools, and real-time collaboration.

[Source](https://github.com/excalidraw/excalidraw)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "excalidraw-excalidraw"
  name       = "myexcalidraw"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
