---
page_title: "eyevinn-wrtc-egress: Symphony Media Bridge WHEP Gateway"
subcategory: "Services"
description: |-
  "Streamline your video services with Eyevinn's WebRTC Egress Endpoint Library.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Symphony Media Bridge WHEP Gateway (`eyevinn-wrtc-egress`)

"Streamline your video services with Eyevinn's WebRTC Egress Endpoint Library. Perfect for standardized streaming with WHEP protocol. Enhance your Symphony Media Bridge connections now!"

[Source](https://github.com/Eyevinn/wrtc-egress)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-wrtc-egress"
  name       = "myegress"

  parameters = {
    SmbUrl    = "..."
    # SmbApiKey = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `SmbUrl` | string | yes |  |
| `SmbApiKey` | string | no |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
