---
page_title: "eyevinn-ograf-editor: OGraf Template Editor"
subcategory: "Services"
description: |-
  Unleash stunning broadcast graphics effortlessly with OGraf Template Editor.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# OGraf Template Editor (`eyevinn-ograf-editor`)

Unleash stunning broadcast graphics effortlessly with OGraf Template Editor. Design professional templates using our intuitive drag-and-drop interface, real-time previews, and code customization. No graphic design skills required!

[Source](https://github.com/Eyevinn/ograf-editor)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-ograf-editor"
  name       = "myeditor"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
