---
page_title: "eyevinn-ephtoken-svc: Ephmeral Token Service"
subcategory: "Services"
description: |-
  Seamlessly integrate with client-side apps by generating ephemeral API tokens for the OpenAI Realtime API.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Ephmeral Token Service (`eyevinn-ephtoken-svc`)

Seamlessly integrate with client-side apps by generating ephemeral API tokens for the OpenAI Realtime API. Simplify authentication and enhance security with this easy-to-install solution today!

[Source](https://github.com/Eyevinn/ephtoken-svc)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-ephtoken-svc"
  name       = "mysvc"

  parameters = {
    OpenAiApiKey = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `OpenAiApiKey` | string | yes |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
