---
page_title: "eyevinn-smb-whip-bridge: Symphony Media Bridge WHIP Gateway"
subcategory: "Services"
description: |-
  Elevate your video streaming with SMB WHIP Bridge! Seamlessly integrate WHIP clients with Symphony Media Bridge SFU for superior media streams.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Symphony Media Bridge WHIP Gateway (`eyevinn-smb-whip-bridge`)

Elevate your video streaming with SMB WHIP Bridge! Seamlessly integrate WHIP clients with Symphony Media Bridge SFU for superior media streams.

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Symphony-Media-Bridge-WHIP-Gateway.html) · [Source](https://github.com/Eyevinn/smb-whip-bridge)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-smb-whip-bridge"
  name       = "mybridge"

  parameters = {
    SmbUrl          = "..."
    # SmbApiKey       = "..."
    # WhepEndpointUrl = "..."
    # WhipApiKey      = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `SmbUrl` | string | yes |  |
| `SmbApiKey` | string | no |  |
| `WhepEndpointUrl` | string | no |  |
| `WhipApiKey` | string | no |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
