---
page_title: "eyevinn-test-adserver: Test Adserver"
subcategory: "Services"
description: |-
  Eyevinn Test Adserver is the ultimate solution for testing CSAI/SSAI stitching and tracking implementation.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Test Adserver (`eyevinn-test-adserver`)

Eyevinn Test Adserver is the ultimate solution for testing CSAI/SSAI stitching and tracking implementation. Open source, easy to use, and flexible for various use cases. Get it now and experience seamless testing!

[Service documentation](https://github.com/Eyevinn/test-adserver) · [Source](https://github.com/Eyevinn/test-adserver)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-test-adserver"
  name       = "myadserver"

  parameters = {
    # MrssOrigin = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `MrssOrigin` | string | no | Configuration option for mrssorigin |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
