---
page_title: "eyevinn-just-go-live: Just Go Live"
subcategory: "Services"
description: |-
  Effortlessly stream live with Just Go Live.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Just Go Live (`eyevinn-just-go-live`)

Effortlessly stream live with Just Go Live. One-click setup, generate RTMP URLs for ease, and engage viewers instantly with HLS streaming. Simplify your broadcasting journey with no fuss, just go live!

[Source](https://github.com/Eyevinn/just-go-live)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-just-go-live"
  name       = "mylive"

  parameters = {
    OscAccessToken = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `OscAccessToken` | string | yes | Your personal access token |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
