---
page_title: "eyevinn-encore-packager: Encore Packager"
subcategory: "Services"
description: |-
  Enhance your transcoding workflow with Encore packager! Run as a service, listen for messages on redis queue, and customize packaging events.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Encore Packager (`eyevinn-encore-packager`)

Enhance your transcoding workflow with Encore packager! Run as a service, listen for messages on redis queue, and customize packaging events. Boost productivity with this versatile tool. VOD pipeline — packages output of Encore transcoding jobs; no live input support.

[Source](https://github.com/Eyevinn/encore-packager)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-encore-packager"
  name       = "mypackager"

  parameters = {
    RedisUrl                = "..."
    OutputFolder            = "..."
    PersonalAccessToken     = "..."
    AwsAccessKeyId          = "..."
    AwsSecretAccessKey      = "..."
    # RedisQueue              = "..."
    # Concurrency             = "..."
    # AwsRegion               = "..."
    # AwsSessionToken         = "..."
    # S3EndpointUrl           = "..."
    # OutputSubfolderTemplate = "..."
    # SkipPackaging           = "true"
    # CallbackUrl             = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `RedisUrl` | string | yes | URL to the Redis server used for message queuing when running as a service |
| `RedisQueue` | string | no | Name of the Redis queue to listen to for packaging job messages |
| `OutputFolder` | string | yes | Base folder for packaging output, with actual output stored in subfolders according to OUTPUT_SUBFOLDER_TEMPLATE |
| `Concurrency` | string | no | Number of concurrent packaging jobs that can be processed simultaneously |
| `PersonalAccessToken` | string | yes | OSC (Open Source Cloud) access token for accessing Encore instances hosted in OSC |
| `AwsAccessKeyId` | string | yes | AWS access key ID for authentication when PACKAGE_OUTPUT_FOLDER is an AWS S3 bucket |
| `AwsSecretAccessKey` | string | yes | AWS secret access key for authentication when PACKAGE_OUTPUT_FOLDER is an AWS S3 bucket |
| `AwsRegion` | string | no | AWS region specification for S3 bucket operations |
| `AwsSessionToken` | string | no | AWS session token for temporary credential authentication with S3 |
| `S3EndpointUrl` | string | no | Custom S3 endpoint URL when PACKAGE_OUTPUT_FOLDER is an S3 bucket not hosted on AWS |
| `OutputSubfolderTemplate` | string | no | Template for subfolder structure relative to PACKAGE_OUTPUT_FOLDER where output will be stored |
| `SkipPackaging` | boolean | no | When enable the output files are copied and a SMIL file is created |
| `CallbackUrl` | string | no | Optional callback service URL for receiving packaging success or failure notifications |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
