---
page_title: "eyevinn-dash-monitor: MPD Stream Monitor"
subcategory: "Services"
description: |-
  Ensure smooth streaming experiences with DASH Stream Monitor, a powerful tool for detecting errors in DASH/MPEG-DASH live streams.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# MPD Stream Monitor (`eyevinn-dash-monitor`)

Ensure smooth streaming experiences with DASH Stream Monitor, a powerful tool for detecting errors in DASH/MPEG-DASH live streams. Its REST API, Prometheus metrics, and Docker readiness make integration seamless.

[Source](https://github.com/Eyevinn/dash-monitor)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-dash-monitor"
  name       = "mymonitor"

  parameters = {
    # nodeEnv = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `nodeEnv` | string | no |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
