---
page_title: "eyevinn-function-probe: Media Probe"
subcategory: "Services"
description: |-
  A serverless media function to obtain media information for a media file or media stream.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Media Probe (`eyevinn-function-probe`)

A serverless media function to obtain media information for a media file or media stream.

[Service documentation](https://github.com/Eyevinn/function-probe) · [Source](https://github.com/Eyevinn/function-probe)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-function-probe"
  name       = "myprobe"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
