---
page_title: "eyevinn-ad-normalizer: Ad Normalizer"
subcategory: "Services"
description: |-
  Optimize your ad delivery with Ad Normalizer! Seamlessly transcode and package VAST creatives for your ad server using a Redis-backed workflow.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Ad Normalizer (`eyevinn-ad-normalizer`)

Optimize your ad delivery with Ad Normalizer! Seamlessly transcode and package VAST creatives for your ad server using a Redis-backed workflow. Ensure efficient media processing and reliable ad streaming.

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Ad-Normalizer.html) · [Source](https://github.com/Eyevinn/ad-normalizer)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-ad-normalizer"
  name       = "mynormalizer"

  parameters = {
    EncoreUrl          = "..."
    AdServerUrl        = "..."
    OutputBucketUrl    = "..."
    # RedisUrl           = "..."
    # KeyRegex           = "..."
    # KeyField           = "..."
    # EncoreProfile      = "..."
    # AssetServerUrl     = "..."
    # JitPackaging       = "true"
    # PackagingQueueName = "..."
    # OscAccessToken     = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `EncoreUrl` | string | yes | URL of the related encore instance |
| `RedisUrl` | string | no | The url to the redis/valkey instance used. Should use the redis protocol and ideally include port |
| `AdServerUrl` | string | yes | The url to the ad server endpoint. For the test ad server the path should be /api/v1/ads |
| `OutputBucketUrl` | string | yes | The url to the output folder for the packaged assets |
| `KeyRegex` | string | no | Defaults to [^a-zA-Z0-9] if not set |
| `KeyField` | string | no | Which field that the normalizer should use as key in valkey/redis. Optional, defaults to universalAdId if not set |
| `EncoreProfile` | string | no | Optional, defaults to "program" if not set |
| `AssetServerUrl` | string | no | Optional, http version of OUTPUT_BUCKET_URL is used if not set |
| `JitPackaging` | boolean | no | Signals wether packaging of ads is done JIT or if completed jobs should be put on the packaging queue. optional, defaults to false if not provided |
| `PackagingQueueName` | string | no | Name of the redis queue used for packaging jobs. Optional, defaults to "package" if not provided |
| `OscAccessToken` | string | no | Access token for Eyevinn Open Source Cloud (OSC) when running Encore in that environment |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
