---
page_title: "eyevinn-function-scenes: Scene Detect Media Function"
subcategory: "Services"
description: |-
  A serverless media function to detect scene changes and extract keyframes in a video file or a stream.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Scene Detect Media Function (`eyevinn-function-scenes`)

A serverless media function to detect scene changes and extract keyframes in a video file or a stream.

[Service documentation](https://github.com/Eyevinn/function-scenes) · [Source](https://github.com/Eyevinn/function-scenes)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-function-scenes"
  name       = "myscenes"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
