---
page_title: "eyevinn-lambda-stitch: HLS VOD Stitcher"
subcategory: "Services"
description: |-
  A proxy to insert ads in an HLS VOD either using manifest manipulation or HLS interstitials
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# HLS VOD Stitcher (`eyevinn-lambda-stitch`)

A proxy to insert ads in an HLS VOD either using manifest manipulation or HLS interstitials

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-HLS-VOD-Stitcher.html) · [Source](https://github.com/Eyevinn/lambda-stitch)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-lambda-stitch"
  name       = "mystitch"

  parameters = {
    # AssetListBaseUrl = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `AssetListBaseUrl` | string | no |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
