---
page_title: "eyevinn-img-alt-gen: Image Description Generator"
subcategory: "Services"
description: |-
  Enhance image accessibility effortlessly with our Image Description Generator.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Image Description Generator (`eyevinn-img-alt-gen`)

Enhance image accessibility effortlessly with our Image Description Generator. Utilize OpenAI's prowess to create precise alt tags instantly, making your visuals more inclusive and SEO-friendly!

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Image-Description-Generator.html) · [Source](https://github.com/Eyevinn/img-alt-gen)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-img-alt-gen"
  name       = "mygen"

  parameters = {
    OpenaiApiKey = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `OpenaiApiKey` | string | yes |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
