---
page_title: "eyevinn-docker-testsrc-hls-live: Test Source HLS Live"
subcategory: "Services"
description: |-
  Effortlessly create live HLS test streams with the docker-testsrc-hls-live image.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Test Source HLS Live (`eyevinn-docker-testsrc-hls-live`)

Effortlessly create live HLS test streams with the docker-testsrc-hls-live image. Powered by FFmpeg, it's a must-have for developers crafting and testing video applications in real-time streaming environments.

[Source](https://github.com/Eyevinn/docker-testsrc-hls-live)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-docker-testsrc-hls-live"
  name       = "mylive"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
