---
page_title: "eyevinn-channel-scheduler: Channel Engine Scheduler"
subcategory: "Services"
description: |-
  Streamline your video content scheduling with Channel Scheduler! Experience a professional broadcast-style interface to create and manage linear TV channel schedules in real-time.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Channel Engine Scheduler (`eyevinn-channel-scheduler`)

Streamline your video content scheduling with Channel Scheduler! Experience a professional broadcast-style interface to create and manage linear TV channel schedules in real-time. Ideal for seamless online broadcast management!

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Channel-Engine-Scheduler.html) · [Source](https://github.com/Eyevinn/channel-scheduler)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-channel-scheduler"
  name       = "myscheduler"

  sensitive_parameters = {
    OscAccessToken = var.osc_access_token
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `OscAccessToken` | string | yes | For launching Channel Engine instances enter your personal access token Sensitive, set it in `sensitive_parameters`. |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
