---
page_title: "eyevinn-hls-monitor: HLS Stream Monitor"
subcategory: "Services"
description: |-
  Service to monitor one or more HLS-streams for manifest errors and inconsistencies.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# HLS Stream Monitor (`eyevinn-hls-monitor`)

Service to monitor one or more HLS-streams for manifest errors and inconsistencies.

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-HLS-Stream-Monitor.html) · [Source](https://github.com/Eyevinn/hls-monitor)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-hls-monitor"
  name       = "mymonitor"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
