---
page_title: "eyevinn-wasm-runner: WASM Runner"
subcategory: "Services"
description: |-
  Revolutionize your app deployment with wasm-runner! Seamlessly download and execute WASM files within Docker using the wasmtime runtime.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# WASM Runner (`eyevinn-wasm-runner`)

Revolutionize your app deployment with wasm-runner! Seamlessly download and execute WASM files within Docker using the wasmtime runtime. Perfect for efficient, cross-platform applications.

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-WASM-Runner.html) · [Source](https://github.com/Eyevinn/wasm-runner)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-wasm-runner"
  name       = "myrunner"

  parameters = {
    # WasmUrl        = "..."
    # GithubUrl      = "..."
    # GithubToken    = "..."
    # OscAccessToken = "..."
    # ConfigService  = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `WasmUrl` | string | no | The URL to your WASM code |
| `GithubUrl` | string | no | GitHub repository URL containing a .wasm file. The runner will clone the repository and find the first .wasm file to execute |
| `GithubToken` | string | no | GitHub personal access token for accessing private repositories when using GITHUB_URL option |
| `OscAccessToken` | string | no | Access token for Eyevinn Open Source Cloud (OSC) integration |
| `ConfigService` | string | no | Configuration service endpoint URL for external configuration management |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
