---
page_title: "eyevinn-open-live: Open Live"
subcategory: "Services"
description: |-
  Supercharge your broadcast productions with Open Live's central API server.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Open Live (`eyevinn-open-live`)

Supercharge your broadcast productions with Open Live's central API server. Built with cutting-edge tech, streamline workflows, activate productions swiftly, and manage sources seamlessly. Elevate now!

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Open-Live.html) · [Source](https://github.com/Eyevinn/open-live)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-open-live"
  name       = "mylive"

  parameters = {
    DatabaseUrl    = "..."
    StromUrl       = "..."
    # StromAuthMode  = "osc"
    # OscAccessToken = "..."
    # CorsOrigin     = "..."
  }

  sensitive_parameters = {
    StromAccessToken = var.strom_access_token
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `DatabaseUrl` | string | yes | Full CouchDB connection URL including credentials for data persistence |
| `StromUrl` | string | yes | Base URL of the Strom pipeline engine used for video flow processing |
| `StromAuthMode` | string | no | Authentication mode for connecting to the Strom pipeline engine Default `osc`. |
| `StromAccessToken` | string | no | OSC Personal Access Token for authenticating against OSC-hosted Strom instances Sensitive, set it in `sensitive_parameters`. |
| `OscAccessToken` | string | no | Configuration option for oscaccesstoken |
| `CorsOrigin` | string | no | Allowed CORS origin URL for the studio frontend to enable cross-origin requests to the API server. |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
