---
page_title: "eyevinn-open-builder: Open Builder"
subcategory: "Services"
description: |-
  Elevate your Claude AI experience with Open Builder's intuitive web interface.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Open Builder (`eyevinn-open-builder`)

Elevate your Claude AI experience with Open Builder's intuitive web interface. Streamline interactions, control permissions, and maintain session continuity effortlessly. Simple deployment with Docker!

[Source](https://github.com/Eyevinn/open-builder)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-open-builder"
  name       = "mybuilder"

  parameters = {
    AnthropicApiKey = "..."
    # OscAccessToken  = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `AnthropicApiKey` | string | yes |  |
| `OscAccessToken` | string | no |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
