---
page_title: "eyevinn-open-videocore: Open Videocore"
subcategory: "Services"
description: |-
  Unlock the potential of your media assets with Open Videocore, the headless MAM solution that seamlessly scales in the cloud.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Open Videocore (`eyevinn-open-videocore`)

Unlock the potential of your media assets with Open Videocore, the headless MAM solution that seamlessly scales in the cloud. Effortlessly manage, transcode, package, and deliver content with a single API call!
Open Videocore provisions additional OSC service instances (transcoding, storage, database) depending on the stack you configure it to build — the token rate shown here covers this middleware service only; each instance it provisions is billed separately at its own rate.

[Source](https://github.com/Eyevinn/open-videocore)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-open-videocore"
  name       = "myvideocore"

  parameters = {
    ParameterStoreApiKey = "..."
    ParameterStore       = "..."
    # EncoreMaxInstances   = "..."
    # EncoreMinInstances   = "..."
    # EncoreIdleTimeoutMs  = "..."
  }

  sensitive_parameters = {
    OscAccessToken = var.osc_access_token
    MinioRootPassword = var.minio_root_password
    CouchdbAdminPassword = var.couchdb_admin_password
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `OscAccessToken` | string | yes | Configuration option for oscaccesstoken Sensitive, set it in `sensitive_parameters`. |
| `ParameterStoreApiKey` | string | yes | API key for authentication |
| `ParameterStore` | string | yes | Configuration option for parameterstore |
| `MinioRootPassword` | string | yes | Configuration option for miniorootpassword Sensitive, set it in `sensitive_parameters`. |
| `CouchdbAdminPassword` | string | yes | Database connection configuration Sensitive, set it in `sensitive_parameters`. |
| `EncoreMaxInstances` | string | no | Configuration option for encoremaxinstances |
| `EncoreMinInstances` | string | no | Configuration option for encoremininstances |
| `EncoreIdleTimeoutMs` | string | no | Timeout value in milliseconds or seconds |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
