---
page_title: "eyevinn-app-config-svc: Application Config Service"
subcategory: "Services"
description: |-
  Supercharge your application's efficiency by instantly providing configuration values with our Application Configuration Service.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Application Config Service (`eyevinn-app-config-svc`)

Supercharge your application's efficiency by instantly providing configuration values with our Application Configuration Service. Integrate seamlessly with Redis, leverage cache control, and scale effortlessly.

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-App-Config-Svc.html) · [Source](https://github.com/Eyevinn/app-config-svc)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-app-config-svc"
  name       = "mysvc"

  parameters = {
    RedisUrl               = "..."
    # ParameterEncryptionKey = "..."
    # ConfigApiKey           = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `RedisUrl` | string | yes | Connection URL for the Redis or Redis-compatible key/value store that serves as the backend database for storing application configuration variables |
| `ParameterEncryptionKey` | string | no | Encryption key used to secure sensitive configuration parameters stored in the service |
| `ConfigApiKey` | string | no | API key for authenticating administrative access to the configuration management endpoints |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
