---
page_title: "eyevinn-cat-validate: Common Access Token Validator"
subcategory: "Services"
description: |-
  Enhance your security with Common Access Token Validator, the ultimate validation service for CTA-5007 tokens.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Common Access Token Validator (`eyevinn-cat-validate`)

Enhance your security with Common Access Token Validator, the ultimate validation service for CTA-5007 tokens. Seamlessly integrate with Redis and ClickHouse for efficient token management. Secure your apps today!

[Source](https://github.com/Eyevinn/cat-validate)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-cat-validate"
  name       = "myvalidate"

  parameters = {
    Keys          = "..."
    # Issuer        = "..."
    # RedisUrl      = "..."
    # ClickHouseUrl = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `Keys` | string | yes | Configuration option for keys |
| `Issuer` | string | no | Configuration option for issuer |
| `RedisUrl` | string | no | URL endpoint for external service |
| `ClickHouseUrl` | string | no | URL endpoint for external service |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
