---
page_title: "eyevinn-web-video-review: Video Review"
subcategory: "Services"
description: |-
  Unlock seamless video review with Web Video Review! Stream, analyze, and navigate broadcast videos straight from S3 storage.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Video Review (`eyevinn-web-video-review`)

Unlock seamless video review with Web Video Review! Stream, analyze, and navigate broadcast videos straight from S3 storage. Experience real-time analysis, dynamic timeline navigation, and powerful transcoding with unparalleled ease. Deploy effortlessly using Docker and transform your video reviewing process today!

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Web-Video-Review.html) · [Source](https://github.com/Eyevinn/web-video-review)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-web-video-review"
  name       = "myreview"

  parameters = {
    AccessKeyId     = "..."
    SecretAccessKey = "..."
    Bucket          = "..."
    # s3Region        = "..."
    # s3Endpoint      = "..."
    # awsSessionToken = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `AccessKeyId` | string | yes |  |
| `SecretAccessKey` | string | yes |  |
| `Bucket` | string | yes |  |
| `s3Region` | string | no |  |
| `s3Endpoint` | string | no |  |
| `awsSessionToken` | string | no |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
