---
page_title: "eyevinn-channel-engine-bridge: Channel Engine Bridge"
subcategory: "Services"
description: |-
  Channel Engine Bridge enables seamless pushing of FAST channels from FAST Channel Engine to distribution platforms such as AWS MediaPackage and simplifies the process of pushing channels to a wide ...
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Channel Engine Bridge (`eyevinn-channel-engine-bridge`)

Channel Engine Bridge enables seamless pushing of FAST channels from FAST Channel Engine to distribution platforms such as AWS MediaPackage and simplifies the process of pushing channels to a wide range of distribution networks.

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Channel-Engine-Bridge.html) · [Source](https://github.com/Eyevinn/channel-engine-bridge)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-channel-engine-bridge"
  name       = "mybridge"

  parameters = {
    Source             = "..."
    DestType           = "mediapackage"
    DestUrl            = "..."
    # AwsAccessKeyId     = "..."
    # AwsSecretAccessKey = "..."
    # AwsRegion          = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `Source` | string | yes | URL to source HLS |
| `DestType` | enum | yes | Type of destination Allowed: `mediapackage`, `mediastore`, `s3`. |
| `DestUrl` | string | yes | Destination URL |
| `AwsAccessKeyId` | string | no |  |
| `AwsSecretAccessKey` | string | no |  |
| `AwsRegion` | string | no |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
