---
page_title: "eyevinn-encore-callback-listener: Encore Callback Listener"
subcategory: "Services"
description: |-
  Encore callback listener is a powerful HTTP server that listens for successful job callbacks, posting jobId and Url on a redis queue.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Encore Callback Listener (`eyevinn-encore-callback-listener`)

Encore callback listener is a powerful HTTP server that listens for successful job callbacks, posting jobId and Url on a redis queue. Fully customizable with environment variables. Enhance your project efficiency now! Contact sales@eyevinn.se for further details.

[Source](https://github.com/Eyevinn/encore-callback-listener)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-encore-callback-listener"
  name       = "mylistener"

  parameters = {
    RedisUrl   = "..."
    EncoreUrl  = "..."
    # RedisQueue = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `RedisUrl` | string | yes | URL endpoint for external service |
| `EncoreUrl` | string | yes | URL endpoint for external service |
| `RedisQueue` | string | no | Configuration option for redisqueue |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
