---
page_title: "eyevinn-player-analytics-eventsink: Player Analytics Eventsink"
subcategory: "Services"
description: |-
  Unlock seamless video analytics with Eyevinn Player Analytics Eventsink! Streamline data collection from video players and enhance performance insights.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Player Analytics Eventsink (`eyevinn-player-analytics-eventsink`)

Unlock seamless video analytics with Eyevinn Player Analytics Eventsink! Streamline data collection from video players and enhance performance insights. Experience modular flexibility and AWS integration today!

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Player-Analytics-Eventsink.html) · [Source](https://github.com/Eyevinn/player-analytics-eventsink)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-player-analytics-eventsink"
  name       = "myeventsink"

  parameters = {
    SqsQueueUrl        = "..."
    AwsAccessKeyId     = "..."
    AwsSecretAccessKey = "..."
    # SqsEndpoint        = "..."
    # AllowedOrigins     = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `SqsQueueUrl` | string | yes | The URL of the Amazon SQS queue where validated analytics events will be sent for processing |
| `AwsAccessKeyId` | string | yes | AWS access key ID for authenticating with Amazon Web Services to access SQS and other AWS resources |
| `AwsSecretAccessKey` | string | yes | AWS secret access key for authenticating with Amazon Web Services, used in conjunction with the access key ID |
| `SqsEndpoint` | string | no | Custom SQS endpoint URL, typically used for local development or alternative SQS-compatible services |
| `AllowedOrigins` | string | no | Provide a comma separated list of origins to allow. If empty allow all |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
