---
page_title: "eyevinn-encore-transfer: Encore Transfer"
subcategory: "Services"
description: |-
  Introducing Encore Transfer - the ultimate service for seamless output transfer in a video processing pipeline.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Encore Transfer (`eyevinn-encore-transfer`)

Introducing Encore Transfer - the ultimate service for seamless output transfer in a video processing pipeline. With easy installation and essential environment variables, this service is a game-changer for Open Source Cloud users. Dive into our comprehensive documentation and join our supportive community on Slack. Don't miss out on this opportunity to revolutionize your video workflow with Eyevinn Technology's innovative solution. Get in touch with us for further customization and support options!

[Source](https://github.com/Eyevinn/encore-transfer)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-encore-transfer"
  name       = "mytransfer"

  parameters = {
    RedisUrl                 = "..."
    Output                   = "..."
    OscAccessToken           = "..."
    # RedisQueue               = "..."
    # AwsAccessKeyIdSecret     = "..."
    # AwsSecretAccessKeySecret = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `RedisUrl` | string | yes |  |
| `RedisQueue` | string | no |  |
| `Output` | string | yes |  |
| `OscAccessToken` | string | yes |  |
| `AwsAccessKeyIdSecret` | string | no |  |
| `AwsSecretAccessKeySecret` | string | no |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
