---
page_title: "eyevinn-ai-code-reviewer: AI Code Reviewer"
subcategory: "Services"
description: |-
  Elevate your code quality with AI Code Reviewer! Leverage AI to review your code effortlessly, ensuring top-notch quality.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# AI Code Reviewer (`eyevinn-ai-code-reviewer`)

Elevate your code quality with AI Code Reviewer! Leverage AI to review your code effortlessly, ensuring top-notch quality. Integrate easily with your cloud setup for seamless code enhancement.

[Source](https://github.com/Eyevinn/ai-code-reviewer)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-ai-code-reviewer"
  name       = "myreviewer"

  parameters = {
    OpenAiApiKey = "..."
    # AssistantId  = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `OpenAiApiKey` | string | yes |  |
| `AssistantId` | string | no |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
