---
page_title: "eyevinn-player-analytics-worker: Player Analytics Worker"
subcategory: "Services"
description: |-
  Unlock powerful insights with Eyevinn Player Analytics Worker – the modular framework designed to streamline video player event tracking.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Player Analytics Worker (`eyevinn-player-analytics-worker`)

Unlock powerful insights with Eyevinn Player Analytics Worker – the modular framework designed to streamline video player event tracking. Effortlessly process and store event data, boosting your analytics game!

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Player-Analytics-Worker.html) · [Source](https://github.com/Eyevinn/player-analytics-worker)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-player-analytics-worker"
  name       = "myworker"

  parameters = {
    ClickHouseUrl      = "..."
    SqsQueueUrl        = "..."
    AwsAccessKeyId     = "..."
    AwsSecretAccessKey = "..."
    # SqsEndpoint        = "..."
    # NumWorkers         = "..."
    # BatchSize          = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `ClickHouseUrl` | string | yes | The connection URL for the ClickHouse database where processed analytics events will be stored |
| `SqsQueueUrl` | string | yes | The AWS SQS queue URL from which the worker will poll for analytics events to process |
| `AwsAccessKeyId` | string | yes | AWS access key ID for authenticating with SQS services to read analytics events from the queue |
| `AwsSecretAccessKey` | string | yes | AWS secret access key for authenticating with SQS services to read analytics events from the queue |
| `SqsEndpoint` | string | no | Custom SQS endpoint URL for connecting to SQS services hosted outside of standard AWS regions |
| `NumWorkers` | string | no | The number of worker processes to spawn for processing analytics events from the SQS queue |
| `BatchSize` | string | no | The maximum number of messages to retrieve from the SQS queue in a single batch operation |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
