---
page_title: "eyevinn-encore-ui: SVT Encore GUI"
subcategory: "Services"
description: |-
  Upgrade your video encoding process with Encore UI, a sleek React-based interface for seamless job management.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# SVT Encore GUI (`eyevinn-encore-ui`)

Upgrade your video encoding process with Encore UI, a sleek React-based interface for seamless job management. Enjoy real-time updates, detailed insights, and ultimate control over encoding workflows.

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-SVT-Encore.html) · [Source](https://github.com/Eyevinn/encore-ui)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-encore-ui"
  name       = "myui"

  parameters = {
    EncoreUrl      = "..."
    # OscAccessToken = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `EncoreUrl` | string | yes |  |
| `OscAccessToken` | string | no |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
