---
page_title: "eyevinn-openevents: Open Events"
subcategory: "Services"
description: |-
  Streamline your event management with OpenEvents, the comprehensive platform for dynamic event planning and seamless ticketing.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Open Events (`eyevinn-openevents`)

Streamline your event management with OpenEvents, the comprehensive platform for dynamic event planning and seamless ticketing. Enhance attendee experience with real-time tracking, multiple ticketing options, and secure payment integration, all effortlessly managed through an intuitive dashboard.

[Source](https://github.com/Eyevinn/openevents)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-openevents"
  name       = "myopenevents"

  parameters = {
    stripePublishableKey = "..."
    s3Endpoint           = "..."
    s3Region             = "..."
    s3BucketName         = "..."
    databaseUrl          = "..."
    # smtpHost             = "..."
    # smtpPort             = "..."
    # smtpUser             = "..."
    # fromEmail            = "..."
    # siteName             = "..."
    # siteUrl              = "..."
  }

  sensitive_parameters = {
    nextauthSecret = var.nextauth_secret
    stripeSecretKey = var.stripe_secret_key
    stripeWebhookSecret = var.stripe_webhook_secret
    s3AccessKeyId = var.s3_access_key_id
    s3SecretAccessKey = var.s3_secret_access_key
    smtpPassword = var.smtp_password
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `nextauthSecret` | string | yes | Secret key used by NextAuth.js for encrypting JWT tokens and session data Sensitive, set it in `sensitive_parameters`. |
| `stripeSecretKey` | string | yes | Stripe secret API key for processing online payments Sensitive, set it in `sensitive_parameters`. |
| `stripePublishableKey` | string | yes | Stripe publishable API key for client-side payment form integration |
| `stripeWebhookSecret` | string | yes | Stripe webhook endpoint secret for verifying payment event notifications Sensitive, set it in `sensitive_parameters`. |
| `s3Endpoint` | string | yes | S3-compatible storage endpoint URL for file uploads |
| `s3Region` | string | yes | AWS region or S3-compatible storage region setting |
| `s3BucketName` | string | yes | Name of the S3 bucket for storing uploaded files |
| `s3AccessKeyId` | string | yes | Access key ID for S3-compatible storage authentication Sensitive, set it in `sensitive_parameters`. |
| `s3SecretAccessKey` | string | yes | Secret access key for S3-compatible storage authentication Sensitive, set it in `sensitive_parameters`. |
| `smtpHost` | string | no | SMTP server hostname for sending emails |
| `smtpPort` | string | no | SMTP server port number for email delivery |
| `smtpUser` | string | no | Username for SMTP server authentication |
| `smtpPassword` | string | no | Password for SMTP server authentication Sensitive, set it in `sensitive_parameters`. |
| `fromEmail` | string | no | Email address used as the sender for outgoing emails |
| `siteName` | string | no | Name of the event platform displayed in the application |
| `siteUrl` | string | no | Base URL of the deployed application |
| `databaseUrl` | string | yes | PostgreSQL database connection string |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
