---
page_title: "eyevinn-function-trim: Trim Media"
subcategory: "Services"
description: |-
  A serverless media function to trim single media file or an ABR bundle of media files and upload the output to an S3 bucket.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Trim Media (`eyevinn-function-trim`)

A serverless media function to trim single media file or an ABR bundle of media files and upload the output to an S3 bucket.

[Source](https://github.com/Eyevinn/function-trim)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "eyevinn-function-trim"
  name       = "mytrim"

  parameters = {
    awsRegion          = "..."
    awsAccessKeyId     = "..."
    awsSecretAccessKey = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `awsRegion` | string | yes | AWS Region where output S3 bucket resides |
| `awsAccessKeyId` | string | yes | AWS Access Key Id for S3 bucket access |
| `awsSecretAccessKey` | string | yes | AWS Secret Access Key for S3 bucket access |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
