---
page_title: "ferretdb-ferretdb: Ferret DB"
subcategory: "Services"
description: |-
  FerretDB is an open source alternative to MongoDB that lets your applications keep using MongoDB 5.0+ drivers and tools while storing data in PostgreSQL.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Ferret DB (`ferretdb-ferretdb`)

FerretDB is an open source alternative to MongoDB that lets your applications keep using MongoDB 5.0+ drivers and tools while storing data in PostgreSQL. It works as a proxy: it accepts MongoDB wire protocol (BSON) queries, translates them to SQL, and uses PostgreSQL with the DocumentDB extension as the database engine. In many cases it can act as a drop-in replacement, with compatibility and performance improving over time.

With Eyevinn OSC, you can consume FerretDB as a managed service instead of running and wiring together FerretDB plus PostgreSQL/DocumentDB yourself. OSC handles provisioning and day-to-day service operation so you can focus on your application, while still connecting with the same MongoDB clients and workflows you already use.

Because it’s part of OSC, managed FerretDB fits into the rest of your OSC environment: you get a consistent way to spin up services quickly and keep your stack based on open source components without taking on the operational overhead of self-hosting.

[Source](https://github.com/FerretDB/FerretDB)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "ferretdb-ferretdb"
  name       = "myferretdb"

  parameters = {
    # LogLevel = "..."
  }

  sensitive_parameters = {
    PostgresqlUrl = var.postgresql_url
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `PostgresqlUrl` | string | yes | Sensitive, set it in `sensitive_parameters`. |
| `LogLevel` | string | no |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
