---
page_title: "freescout-help-desk-freescout: FreeScout"
subcategory: "Services"
description: |-
  Discover FreeScout, the ultimate self-hosted help desk solution.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# FreeScout (`freescout-help-desk-freescout`)

Discover FreeScout, the ultimate self-hosted help desk solution. Enjoy robust features akin to Zendesk & Help Scout without conceding privacy or control. Fully customizable, mobile-friendly, and free!

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-FreeScout.html) · [Source](https://github.com/freescout-help-desk/freescout)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "freescout-help-desk-freescout"
  name       = "myfreescout"

  parameters = {
    DbUrl         = "..."
    AdminEmail    = "..."
    AdminPassword = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `DbUrl` | string | yes | Mysql Database url in the format mysql://<user>:<password>@<host>:<port>/<database> |
| `AdminEmail` | string | yes | Email address for the administrator account that will be created during FreeScout installation. This will be the primary admin user who can manage the help desk system. |
| `AdminPassword` | string | yes | Password for the administrator account that will be created during FreeScout installation. This should be a secure password for the primary admin user. |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
