---
page_title: "grafana-grafana: Grafana"
subcategory: "Services"
description: |-
  Transform your organization's data viewing experience with Grafana's cutting-edge visualizations and dynamic dashboards.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Grafana (`grafana-grafana`)

Transform your organization's data viewing experience with Grafana's cutting-edge visualizations and dynamic dashboards. Effortlessly explore metrics, logs, and receive alerts tailored precisely for powerful insights.

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Grafana.html) · [Source](https://github.com/grafana/grafana)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "grafana-grafana"
  name       = "mygrafana"

  parameters = {
    # PluginsPreinstall = "..."
    # AllowEmbedOrigins = "..."
    # AnonymousEnabled  = "true"
    # Datasources       = "..."
    # DashboardUrls     = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `PluginsPreinstall` | string | no | Provide a list of plugins to pre install |
| `AllowEmbedOrigins` | string | no | Web origin allowed to embed in an iframe |
| `AnonymousEnabled` | boolean | no | Enable anonymous access |
| `Datasources` | string | no | Datasource to automatically provision at startup in the form, example: "influx:influxdb:http://influxdb:8086;admin;secret" Pattern `([a-zA-Z0-9_-]+:[a-zA-Z0-9_-]+:https?://[a-zA-Z0-9_.-]+(:[0-9]+)?(/[a-zA-Z0-9_./%-]*)?(;[^;\|]+;[^;\|]+)?(\\|[a-zA-Z0-9_-]+:[a-zA-Z0-9_-]+:https?://[a-zA-Z0-9_.-]+(:[0-9]+)?(/[a-zA-Z0-9_./%-]*)?(;[^;\|]+;[^;\|]+)?)*)`. |
| `DashboardUrls` | string | no | URL endpoint for external service |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
