---
page_title: "gwuhaolin-livego: Livego"
subcategory: "Services"
description: |-
  Experience the power of simplicity and efficiency with our live broadcast server! Easy to install and use, built in pure Golang for high performance.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Livego (`gwuhaolin-livego`)

Experience the power of simplicity and efficiency with our live broadcast server! Easy to install and use, built in pure Golang for high performance. Supports RTMP, AMF, HLS, HTTP-FLV protocols, FLV, TS containers, H264, AAC, MP3 encoding formats. Stream and playback seamlessly with just a few simple steps. Get your hands on this amazing product now!

[Source](https://github.com/gwuhaolin/livego)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "gwuhaolin-livego"
  name       = "mylivego"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
