---
page_title: "itzg-docker-minecraft-server: Minecraft Server"
subcategory: "Services"
description: |-
  Experience seamless Minecraft server management with our Docker solution! Easily deploy, customize, and scale your servers with robust support for different versions, mods, and plugins.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Minecraft Server (`itzg-docker-minecraft-server`)

Experience seamless Minecraft server management with our Docker solution! Easily deploy, customize, and scale your servers with robust support for different versions, mods, and plugins. Perfect for dedicated gamers and server admins alike!

[Source](https://github.com/itzg/docker-minecraft-server)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "itzg-docker-minecraft-server"
  name       = "myserver"

  parameters = {
    AcceptEula                 = "true"
    RconPassword               = "..."
    Mode                       = "..."
    # Difficulty                 = "..."
    # MaxWorldSize               = "..."
    # AllowNether                = "true"
    # AnnouncePlayerAchievements = "true"
    # EnableCommandBlock         = "true"
    # ForceGamemode              = "true"
    # GeneralStructures          = "true"
    # Hardcore                   = "true"
    # SpawnAnimals               = "true"
    # SpawnMonsters              = "true"
    # SpawnNpcs                  = "true"
    # Seed                       = "..."
    # MaxPlayers                 = "..."
    # Type                       = "..."
    # Pvp                        = "..."
    # OnlineMode                 = "..."
    # Memory                     = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `AcceptEula` | boolean | yes | Accepts the Minecraft End User License Agreement (EULA). Must be set to true to run the server legally. |
| `RconPassword` | string | yes | Sets the password for RCON (Remote Console) access to the server, allowing remote administration and command execution. |
| `Mode` | string | yes | Sets the game mode for the server (survival, creative, adventure, or spectator). |
| `Difficulty` | string | no | Sets the difficulty level of the server (peaceful, easy, normal, or hard). |
| `MaxWorldSize` | string | no | Sets the maximum radius of the world border in blocks. Players cannot move beyond this boundary. |
| `AllowNether` | boolean | no | Enables or disables access to the Nether dimension. |
| `AnnouncePlayerAchievements` | boolean | no | Controls whether player achievements are announced to all players on the server. |
| `EnableCommandBlock` | boolean | no | Enables or disables command blocks on the server. |
| `ForceGamemode` | boolean | no | Forces players to join in the default game mode and prevents them from changing it. |
| `GeneralStructures` | boolean | no | Controls whether structures like villages, dungeons, and other generated structures appear in the world. |
| `Hardcore` | boolean | no | Enables hardcore mode where players are banned from the server when they die. |
| `SpawnAnimals` | boolean | no | Controls whether passive animals (cows, sheep, chickens, etc.) spawn naturally in the world. |
| `SpawnMonsters` | boolean | no | Controls whether hostile monsters (zombies, creepers, skeletons, etc.) spawn naturally in the world. |
| `SpawnNpcs` | boolean | no | Controls whether NPCs like villagers spawn naturally in the world. |
| `Seed` | string | no | Configuration option for seed |
| `MaxPlayers` | string | no | Configuration option for maxplayers |
| `Type` | string | no | Configuration option for type |
| `Pvp` | string | no | Configuration option for pvp |
| `OnlineMode` | string | no | Configuration option for onlinemode |
| `Memory` | string | no | Configuration option for memory |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
