---
page_title: "itzg-docker-minecraft-bedrock-server: Minecraft Server (Bedrock)"
subcategory: "Services"
description: |-
  Unleash the full potential of multiplayer gaming with Itzg's Minecraft Bedrock Server Docker.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Minecraft Server (Bedrock) (`itzg-docker-minecraft-bedrock-server`)

Unleash the full potential of multiplayer gaming with Itzg's Minecraft Bedrock Server Docker. Effortlessly run and upgrade your server with cutting-edge game features. Your world, your rules—simplified!

[Source](https://github.com/itzg/docker-minecraft-bedrock-server)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "itzg-docker-minecraft-bedrock-server"
  name       = "myserver"

  parameters = {
    # GameMode   = "..."
    # MaxPlayers = "..."
    # LevelType  = "..."
    # Variables  = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `GameMode` | string | no | Sets the game mode for the Bedrock server, controlling the gameplay experience for players |
| `MaxPlayers` | string | no | Defines the maximum number of players that can connect to the server simultaneously |
| `LevelType` | string | no | Specifies the type of world/level to generate for the server |
| `Variables` | string | no | Allows setting custom server variables as comma-separated key-value pairs or full JSON string for advanced server configuration |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
