---
page_title: "joeldelpilar-tic-tac-vue: Tic Tac Vue"
subcategory: "Services"
description: |-
  Discover Tic Tac Vue - the ultimate way to enjoy classic Tic Tac Toe! This engaging game is built with Vue 3, offering smooth gameplay and a modern user interface.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Tic Tac Vue (`joeldelpilar-tic-tac-vue`)

Discover Tic Tac Vue - the ultimate way to enjoy classic Tic Tac Toe! This engaging game is built with Vue 3, offering smooth gameplay and a modern user interface. Perfect for quick fun!

[Source](https://github.com/JoeldelPilar/Tic-Tac-Vue)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "joeldelpilar-tic-tac-vue"
  name       = "myvue"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
