---
page_title: "juiceandthejoe-todo-list-vibe: Todo List Vibe"
subcategory: "Services"
description: |-
  Experience seamless task management with Todo List Vibe.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Todo List Vibe (`juiceandthejoe-todo-list-vibe`)

Experience seamless task management with Todo List Vibe. This modern, responsive app features full CRUD capabilities, intuitive filtering, and a sleek UI. Perfect for both mobile and desktop use!

[Source](https://github.com/JuiceAndTheJoe/todo-list-vibe)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "juiceandthejoe-todo-list-vibe"
  name       = "myvibe"

  parameters = {
    databaseUrl = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `databaseUrl` | string | yes |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
