---
page_title: "keycloak-keycloak: Keycloak"
subcategory: "Services"
description: |-
  Effortlessly add authentication to your applications with Keycloak.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Keycloak (`keycloak-keycloak`)

Effortlessly add authentication to your applications with Keycloak. Secure services, manage users, and implement strong authentication—all with minimal setup. Transform your identity management now!

[Source](https://github.com/keycloak/keycloak)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "keycloak-keycloak"
  name       = "mykeycloak"

  parameters = {
    DatabaseUrl = "..."
    AdminUser   = "..."
  }

  sensitive_parameters = {
    AdminPassword = var.admin_password
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `DatabaseUrl` | string | yes |  |
| `AdminUser` | string | yes |  |
| `AdminPassword` | string | yes | Sensitive, set it in `sensitive_parameters`. |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
