---
page_title: "louislam-uptime-kuma: Uptime Kuma"
subcategory: "Services"
description: |-
  Experience seamless uptime monitoring with Uptime Kuma.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Uptime Kuma (`louislam-uptime-kuma`)

Experience seamless uptime monitoring with Uptime Kuma. This intuitive, self-hosted tool tracks diverse services and delivers rapid notifications to ensure your operations remain uninterrupted.

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Uptime-Kuma.html) · [Source](https://github.com/louislam/uptime-kuma)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "louislam-uptime-kuma"
  name       = "mykuma"

  parameters = {
    DatabaseUrl = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `DatabaseUrl` | string | yes |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
