---
page_title: "matomo-org-matomo: Matomo"
subcategory: "Services"
description: |-
  Unleash the power of analytics with Matomo.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Matomo (`matomo-org-matomo`)

Unleash the power of analytics with Matomo. Own your data with this feature-rich open-source alternative to Google Analytics. Easy installation, real-time stats, and privacy-driven, used by millions!

[Source](https://github.com/matomo-org/matomo)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "matomo-org-matomo"
  name       = "mymatomo"

  parameters = {
    # DatabaseHost         = "..."
    # DatabaseAdapter      = "..."
    # DatabaseTablesPrefix = "..."
    # DatabaseUsername     = "..."
    # DatabasePassword     = "..."
    # DatabaseDbName       = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `DatabaseHost` | string | no |  |
| `DatabaseAdapter` | string | no |  |
| `DatabaseTablesPrefix` | string | no |  |
| `DatabaseUsername` | string | no |  |
| `DatabasePassword` | string | no |  |
| `DatabaseDbName` | string | no |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
