---
page_title: "meilisearch-meilisearch: Meilisearch"
subcategory: "Services"
description: |-
  Transform your search experience with Meilisearch, the lightning-fast, intuitive search engine that integrates seamlessly into your apps.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Meilisearch (`meilisearch-meilisearch`)

Transform your search experience with Meilisearch, the lightning-fast, intuitive search engine that integrates seamlessly into your apps. Boost efficiency with advanced features like hybrid search, typo tolerance, and filtering.

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Meilisearch.html) · [Source](https://github.com/meilisearch/meilisearch)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "meilisearch-meilisearch"
  name       = "mymeilisearch"

  sensitive_parameters = {
    MasterKey = var.master_key
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `MasterKey` | string | yes | The master API key used for authentication and security management in Meilisearch. This key provides full access to all Meilisearch operations and is used to create other API keys with fine-grained permissions. Pattern `^.{16,}$`. Sensitive, set it in `sensitive_parameters`. |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
