---
page_title: "mickael-kerjean-filestash: Filestash"
subcategory: "Services"
description: |-
  Transform your data management with Filestash, a versatile file manager that integrates seamlessly with multiple cloud services and protocols.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Filestash (`mickael-kerjean-filestash`)

Transform your data management with Filestash, a versatile file manager that integrates seamlessly with multiple cloud services and protocols. Enjoy blazing speed, user-friendly interfaces, and plugin flexibility.

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Filestash.html) · [Source](https://github.com/mickael-kerjean/filestash)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "mickael-kerjean-filestash"
  name       = "myfilestash"

  parameters = {
    # AdminPassword      = "..."
    # ConfigSecret       = "..."
    # DropboxClientId    = "..."
    # GdriveClientId     = "..."
    # GdriveClientSecret = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `AdminPassword` | string | no | Sets the password for administrative access to the Filestash backend configuration interface, which allows management of storage backends, authentication settings, plugins, and system configuration. |
| `ConfigSecret` | string | no | A secret key used for encrypting and securing configuration data, session tokens, and other sensitive information within the Filestash application. |
| `DropboxClientId` | string | no | The OAuth2 client ID for Dropbox integration, required to enable Dropbox as a storage backend in Filestash's plugin-driven architecture. |
| `GdriveClientId` | string | no | The OAuth2 client ID for Google Drive integration, required to enable Google Drive as a storage backend through Filestash's storage plugin system. |
| `GdriveClientSecret` | string | no | The OAuth2 client secret for Google Drive integration, used together with the client ID to authenticate and authorize access to Google Drive storage. |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
