---
page_title: "mtlynch-picoshare: PicoShare"
subcategory: "Services"
description: |-
  Simplify file sharing with PicoShare! Instantly create direct download links without ads, file restrictions, or resizing hassles.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# PicoShare (`mtlynch-picoshare`)

Simplify file sharing with PicoShare! Instantly create direct download links without ads, file restrictions, or resizing hassles. Share any file, any size, effortlessly and securely. Try PicoShare today!

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-PicoShare.html) · [Source](https://github.com/mtlynch/picoshare)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "mtlynch-picoshare"
  name       = "mypicoshare"

  parameters = {
    SharedSecret = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `SharedSecret` | string | yes | Specifies a passphrase for the admin user to log in to PicoShare. This is required for authentication to access the admin features of the application. |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
