---
page_title: "nextcloud-server: Nextcloud"
subcategory: "Services"
description: |-
  Empower your data with Nextcloud! Securely store, sync, and share your files, contacts, and calendars across devices.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Nextcloud (`nextcloud-server`)

Empower your data with Nextcloud! Securely store, sync, and share your files, contacts, and calendars across devices. With robust security, expandability, and ease of use, your data thrives effortlessly.

[Source](https://github.com/nextcloud/server)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "nextcloud-server"
  name       = "myserver"

  parameters = {
    AdminUser     = "..."
    AdminPassword = "..."
    # DatabaseUrl   = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `AdminUser` | string | yes | Choose an admin username |
| `AdminPassword` | string | yes | Choose an admin password |
| `DatabaseUrl` | string | no | Database connection configuration |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
