---
page_title: "nolltre-lab-test-prep-quiz: Test Prep Quiz"
subcategory: "Services"
description: |-
  Elevate your events with Test Prep Quiz! Engage and learn with real-time multiplayer quizzes, featuring themed games, avatars, live scoreboards, and Chromecast support.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Test Prep Quiz (`nolltre-lab-test-prep-quiz`)

Elevate your events with Test Prep Quiz! Engage and learn with real-time multiplayer quizzes, featuring themed games, avatars, live scoreboards, and Chromecast support. Ideal for education and entertainment!

[Source](https://github.com/nolltre-lab/test-prep-quiz)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "nolltre-lab-test-prep-quiz"
  name       = "myquiz"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
