---
page_title: "olawalejuwonm-anomalydetector: Anomaly Detector"
subcategory: "Services"
description: |-
  Safeguard your space with Anomaly Detector, a cutting-edge video surveillance solution.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Anomaly Detector (`olawalejuwonm-anomalydetector`)

Safeguard your space with Anomaly Detector, a cutting-edge video surveillance solution. Experience real-time anomaly detection using advanced computer vision, ensuring privacy and reducing false alarms. Enhance security efficiently!

[Source](https://github.com/olawalejuwonm/AnomalyDetector)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "olawalejuwonm-anomalydetector"
  name       = "myanomalydetector"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
