---
page_title: "opf-openproject: OpenProject"
subcategory: "Services"
description: |-
  Elevate team productivity with OpenProject, the ultimate web-based project management tool.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# OpenProject (`opf-openproject`)

Elevate team productivity with OpenProject, the ultimate web-based project management tool. Seamlessly plan, collaborate, and track your projects with features tailored for agile, scrum, and budgeting excellence.

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Open-Project.html) · [Source](https://github.com/opf/openproject)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "opf-openproject"
  name       = "myopenproject"

  parameters = {
    DatabaseUrl = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `DatabaseUrl` | string | yes | PSQL Db Url: postgres://USER:PWD@IP:PORT/DB |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
