---
page_title: "oss-apps-dynamic-og: Dynamic OG"
subcategory: "Services"
description: |-
  Instantly enhance your content with Dynamic OG's AI-powered dynamic Open Graph images! Save time on design, and choose from weekly template updates to keep your website visually engaging and fresh.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Dynamic OG (`oss-apps-dynamic-og`)

Instantly enhance your content with Dynamic OG's AI-powered dynamic Open Graph images! Save time on design, and choose from weekly template updates to keep your website visually engaging and fresh.

[Source](https://github.com/oss-apps/dynamic-og)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "oss-apps-dynamic-og"
  name       = "myog"

  parameters = {
    # nextBeamAnalyticsId = "..."
    # nextDocsAiId        = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `nextBeamAnalyticsId` | string | no | Configuration ID for Beam Analytics integration to track website usage and performance metrics for your Dynamic OG application |
| `nextDocsAiId` | string | no | Configuration ID for DocsAI chatbot integration to enhance user interaction and provide automated assistance within your Dynamic OG application |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
