---
page_title: "ossrs-srs: Simple Realtime Server"
subcategory: "Services"
description: |-
  Experience high-efficiency video streaming with SRS/6.0.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Simple Realtime Server (`ossrs-srs`)

Experience high-efficiency video streaming with SRS/6.0. Stream seamlessly with essential features included. 
Transform your streaming experience now! Explore RTMP, HLS, HTTP-FLV, SRT, MPEG-DASH protocols, and more.
Get started easily!

[Source](https://github.com/ossrs/srs)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "ossrs-srs"
  name       = "mysrs"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
