---
page_title: "owncast-owncast: owncast"
subcategory: "Services"
description: |-
  Revolutionize your live streaming experience with Owncast! Take control over your content, interface, and audience with this self-hosted, open-source platform.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# owncast (`owncast-owncast`)

Revolutionize your live streaming experience with Owncast! Take control over your content, interface, and audience with this self-hosted, open-source platform. Explore the possibilities today.

[Service documentation](https://owncast.online/quickstart/configure/) · [Source](https://github.com/owncast/owncast)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "owncast-owncast"
  name       = "myowncast"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
