---
page_title: "pgvector-pgvector: Postgres Vector"
subcategory: "Services"
description: |-
  Enhance your database with pgvector's robust vector similarity search integrated into Postgres.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Postgres Vector (`pgvector-pgvector`)

Enhance your database with pgvector's robust vector similarity search integrated into Postgres. Effortlessly manage vectors alongside traditional data and execute advanced nearest neighbor searches with ease.

[Source](https://github.com/pgvector/pgvector)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "pgvector-pgvector"
  name       = "mypgvector"

  parameters = {
    PostgresPassword   = "..."
    # PostgresUser       = "..."
    # PostgresDb         = "..."
    # PostgresInitDbArgs = "..."
    # PostgresInitDbSql  = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `PostgresPassword` | string | yes | Sets the password for the PostgreSQL database superuser. This is required to secure access to the database instance. |
| `PostgresUser` | string | no | Specifies the name of the PostgreSQL superuser account to create. If not provided, defaults to 'postgres'. |
| `PostgresDb` | string | no | Sets the name of the default database to create when the PostgreSQL instance starts. If not specified, the database name will match the user name. |
| `PostgresInitDbArgs` | string | no | Provides additional command-line arguments to pass to the 'initdb' command during database cluster initialization. |
| `PostgresInitDbSql` | string | no | Specifies SQL commands to execute during database initialization, such as creating extensions or setting up initial schema. |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
