---
page_title: "plausible-analytics: Plausible Analytics"
subcategory: "Services"
description: |-
  Elevate your data privacy with Plausible Analytics.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Plausible Analytics (`plausible-analytics`)

Elevate your data privacy with Plausible Analytics. Get simple, clutter-free insights without compromising user privacy. Enjoy an easy, lightweight, and privacy-focused Google Analytics alternative!

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Plausible.html) · [Source](https://github.com/plausible/analytics)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "plausible-analytics"
  name       = "myanalytics"

  parameters = {
    PostgreSQLUrl   = "..."
    ClickHouseDbUrl = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `PostgreSQLUrl` | string | yes | Database connection configuration |
| `ClickHouseDbUrl` | string | yes | Database connection configuration |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
