---
page_title: "poundifdef-smoothmq: SmoothMQ"
subcategory: "Services"
description: |-
  Introducing SmoothMQ, the ultimate drop-in replacement for SQS! Enhance your developer experience with a functional UI, observability, tracing, scheduling, and rate-limiting.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# SmoothMQ (`poundifdef-smoothmq`)

Introducing SmoothMQ, the ultimate drop-in replacement for SQS! Enhance your developer experience with a functional UI, observability, tracing, scheduling, and rate-limiting. Run your own private SQS on any cloud effortlessly.

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-SmoothMQ.html) · [Source](https://github.com/poundifdef/SmoothMQ)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "poundifdef-smoothmq"
  name       = "mysmoothmq"

  parameters = {
    # AccessKey = "..."
    # SecretKey = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `AccessKey` | string | no | AWS-compatible access key ID for authenticating with the SmoothMQ server. This credential is used by SQS clients to connect to your private SmoothMQ instance. |
| `SecretKey` | string | no | AWS-compatible secret access key that pairs with the access key ID for client authentication. This is the private portion of the credential pair used to secure access to your SmoothMQ queues. |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
