---
page_title: "psumiya-option-insights: Option Insights"
subcategory: "Services"
description: |-
  Transform your trading data into actionable insights with Option Insights! Visualize performance, track trends, and analyze strategies—all in your browser with total privacy.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Option Insights (`psumiya-option-insights`)

Transform your trading data into actionable insights with Option Insights! Visualize performance, track trends, and analyze strategies—all in your browser with total privacy. No data leaves your device!

[Source](https://github.com/psumiya/option-insights)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "psumiya-option-insights"
  name       = "myinsights"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
