---
page_title: "realeyes-media-moe-replay: MOE Replay"
subcategory: "Services"
description: |-
  Transform live video streams instantly with MOE REPlay.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# MOE Replay (`realeyes-media-moe-replay`)

Transform live video streams instantly with MOE REPlay. Perfect for creating live HLS manifests on the fly. Enhance your streaming service now!

[Source](https://github.com/realeyes-media/moe-replay)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "realeyes-media-moe-replay"
  name       = "myreplay"
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

This service takes no parameters besides `name`.

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
