---
page_title: "roundcube-roundcubemail: Roundcube Webmail"
subcategory: "Services"
description: |-
  Transform your email experience with Roundcube Webmail! Enjoy a browser-based multilang IMAP client with intuitive design, customizable skins, and extensive plugin support.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Roundcube Webmail (`roundcube-roundcubemail`)

Transform your email experience with Roundcube Webmail! Enjoy a browser-based multilang IMAP client with intuitive design, customizable skins, and extensive plugin support. Efficiency meets versatility!

[Service documentation](https://docs.osaas.io/osaas.wiki/Service%3A-Roundcube-Webmail.html) · [Source](https://github.com/roundcube/roundcubemail)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "roundcube-roundcubemail"
  name       = "myroundcubemail"

  parameters = {
    ImapAddress = "..."
    ImapPort    = "993"
    SmtpAddress = "..."
    SmtpPort    = "587"
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `ImapAddress` | string | yes | Imap URL (e.g. ssl://mail.osaas.io) |
| `ImapPort` | string | yes | Port number for the service to listen on Default `993`. |
| `SmtpAddress` | string | yes | Smtp URL (e.g. tls://mail.osaas.io) |
| `SmtpPort` | string | yes | Port number for the service to listen on Default `587`. |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
