---
page_title: "searxng-searxng: SearXNG"
subcategory: "Services"
description: |-
  Experience the power of privacy with SearXNG, a customizable metasearch engine delivering unmatched confidentiality.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# SearXNG (`searxng-searxng`)

Experience the power of privacy with SearXNG, a customizable metasearch engine delivering unmatched confidentiality. Explore the web securely with our easy setup and extensive admin tools.

[Source](https://github.com/searxng/searxng)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "searxng-searxng"
  name       = "mysearxng"

  parameters = {
    # AutoComplete = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `AutoComplete` | string | no |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
