---
page_title: "srperens-uturn: uTURN"
subcategory: "Services"
description: |-
  Simplify your WebRTC deployments with uTURN—a streamlined TURN server that routes all traffic through a single UDP port.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# uTURN (`srperens-uturn`)

Simplify your WebRTC deployments with uTURN—a streamlined TURN server that routes all traffic through a single UDP port. Ideal for Kubernetes and restrictive environments, uTURN keeps communication seamless and efficient.

[Source](https://github.com/srperens/uturn)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "srperens-uturn"
  name       = "myuturn"

  parameters = {
    # Realm = "..."
    # Users = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `Realm` | string | no | Specifies the TURN realm used for authentication purposes. The realm is a string that identifies the authentication domain for TURN server credentials. |
| `Users` | string | no | Defines user credentials for TURN authentication in 'username:password' format. Multiple users can be specified by repeating this option. |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
