---
page_title: "supercorp-ai-supergateway: Supergateway"
subcategory: "Services"
description: |-
  Unlock seamless stdio MCP server connectivity with Supergateway! Run servers over SSE effortlessly, ideal for remote access and debugging.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Supergateway (`supercorp-ai-supergateway`)

Unlock seamless stdio MCP server connectivity with Supergateway! Run servers over SSE effortlessly, ideal for remote access and debugging. Start with one command to deliver powerful, real-time interactions!

[Source](https://github.com/supercorp-ai/supergateway)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "supercorp-ai-supergateway"
  name       = "mysupergateway"

  parameters = {
    McpServer = "..."
    # EnvVars   = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `McpServer` | string | yes |  |
| `EnvVars` | string | no |  |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
