---
page_title: "supertokens-supertokens-core: SuperTokens"
subcategory: "Services"
description: |-
  Boost your app's security and user experience with SuperTokens' open-source auth solution.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# SuperTokens (`supertokens-supertokens-core`)

Boost your app's security and user experience with SuperTokens' open-source auth solution. Integrate seamless login, multi-factor auth, and session management, all with no vendor lock-in.

[Source](https://github.com/supertokens/supertokens-core)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "supertokens-supertokens-core"
  name       = "mycore"

  parameters = {
    databaseUrl              = "..."
    # bulkMigrationCronEnabled = "true"
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `bulkMigrationCronEnabled` | boolean | no | Enables or disables the bulk migration cron job that handles periodic data migration tasks in the SuperTokens core service |
| `databaseUrl` | string | yes | Specifies the database connection URL for SuperTokens core to connect to the underlying database for storing authentication data and session information |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
