---
page_title: "svensson00-spectercrm: Specter CRM"
subcategory: "Services"
description: |-
  Revolutionize your CRM management with SpecterCRM's seamless multi-tenant SaaS architecture! Effortlessly handle organizations, contacts, and deals while benefiting from advanced deduplication, com...
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Specter CRM (`svensson00-spectercrm`)

Revolutionize your CRM management with SpecterCRM's seamless multi-tenant SaaS architecture! Effortlessly handle organizations, contacts, and deals while benefiting from advanced deduplication, comprehensive reporting, and robust API integrations. Upgrade to the all-in-one CRM solution today for streamlined, data-driven success!

[Source](https://github.com/svensson00/SpecterCRM)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "svensson00-spectercrm"
  name       = "myspectercrm"

  parameters = {
    DatabaseUrl = "..."
    # CorsOrigin  = "..."
  }

  sensitive_parameters = {
    JwtSecret = var.jwt_secret
    RefreshTokenSecret = var.refresh_token_secret
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `DatabaseUrl` | string | yes | PostgreSQL database connection string used by Prisma ORM to connect to the database. This is the primary database configuration for the multi-tenant CRM application. |
| `JwtSecret` | string | no | Secret key used to sign and verify JWT access tokens for user authentication. This ensures the security and integrity of authentication tokens. Sensitive, set it in `sensitive_parameters`. |
| `RefreshTokenSecret` | string | no | Secret key used to sign and verify JWT refresh tokens, which are used to obtain new access tokens without requiring users to re-authenticate. Sensitive, set it in `sensitive_parameters`. |
| `CorsOrigin` | string | no | Defines the allowed origins for Cross-Origin Resource Sharing (CORS) requests to the API. This controls which frontend URLs can make requests to the backend. |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
