---
page_title: "swagger-api-swagger-editor: Swagger Editor"
subcategory: "Services"
description: |-
  Next generation Swagger Editor is here! Edit OpenAPI definitions in JSON or YAML format in your browser and preview documentation in real time.
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Swagger Editor (`swagger-api-swagger-editor`)

Next generation Swagger Editor is here! Edit OpenAPI definitions in JSON or YAML format in your browser and preview documentation in real time. Generate valid OpenAPI definitions for full Swagger tooling support. Upgrade to SwaggerEditor@5 for OpenAPI 3.1.0 support and enjoy a brand-new version built from the ground up. Get your Swagger Editor now!

[Source](https://github.com/swagger-api/swagger-editor)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "swagger-api-swagger-editor"
  name       = "myeditor"

  parameters = {
    # ApiDefinitionUrl = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `ApiDefinitionUrl` | string | no | URL endpoint for external service |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
