---
page_title: "temporalio-temporal: Temporal"
subcategory: "Services"
description: |-
  Boost your app's reliability with Temporal! As a durable execution platform, it handles failures and retries seamlessly, empowering developers to build scalable applications without losing producti...
---
<!-- generated by catalogsync from the OSC catalog; do not edit by hand -->

# Temporal (`temporalio-temporal`)

Boost your app's reliability with Temporal! As a durable execution platform, it handles failures and retries seamlessly, empowering developers to build scalable applications without losing productivity.

[Source](https://github.com/temporalio/temporal)

## Example

```terraform
resource "osc_instance" "example" {
  service_id = "temporalio-temporal"
  name       = "mytemporal"

  parameters = {
    DatabaseUrl = "..."
  }
}
```

Commented lines are optional parameters. Values marked `"..."` need a real value. Outputs are `url`, `external_ip`, `external_port` and the raw `instance` document, see the `osc_instance` resource.

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
| `DatabaseUrl` | string | yes | Database connection URL for Temporal server persistence layer. Temporal supports multiple database backends including Cassandra, MySQL, PostgreSQL, and SQLite for storing workflow execution state, history, and metadata. |

The instance `name` must match `^\w+$` and be unique per service within the workspace. OSC lowercases it and allows at most 20 characters.

Parameter values are strings; booleans take `"true"` or `"false"`. Reference an `osc_secret` as `osc_secret.<name>.ref` to keep a value out of the instance configuration. This page is generated from the OSC catalog; the provider validates against the live catalog when planning.
